architecture:
  gate_activation_fn: sigmoid
  gate_neuron_counts:
  - 64
  output_activation_fn: none
  output_feature_count: 1
hyperparameters:
  batch_size: 64
  dropout_rate: null
  grad_clip_norm: 1
  grad_clip_value: null
  lambda_L2: null
  learn_rate: 0.01
  loss_func: MSELoss
  optimizer: adam
  reduction: mean
log_id: logs/2025-06-29_08:22:56_autoregressive_lstm
parameters_fpath: ./params/lstm/autoregressive
specs:
  autoregressive: true
  device_type: cpu
  input_feature_count: 1
  stateful: false
  teacher_forcing: regressive
test:
  show_results: true
  test_dataset_size: 50
train:
  epochs: 50000
  show_loss_plot: true
  train_dataset_size: 50000
