specs:
  multi_out: false
  device_type: "cpu"
  mode: "test"
  pretrained: true
  input_data_dim: [1, 64, 64] # [color_channels, img_height, img_width]

# specs:
#   multi_out: false
#   device_type: "cpu"
#   mode: "train"
#   pretrained: false
#   input_data_dim: [1, 64, 64] # [color_channels, img_height, img_width]

#------------------------------------------------------------------------------------------------------------------------
train:
  epochs: 800
  train_dataset_size: 1000
  show_loss_plot: true

hyperparameters:
  cnn_hyperparameters:
    learn_rate: 0.01
    batch_size: 24
    loss_func: "BCELoss"
    reduction: "mean"
    optimizer: "adam"
    lambda_L2: 0.001 #1e-6
    dropout_rate: ~
  mlp_hyperparameters: 
    learn_rate: 0.01
    optimizer: "adam"
    lambda_L2: 0.001 #1e-6
    dropout_rate: ~

architecture:
  cnn_architecture:
    is_conv_layer: [true, false, true, false]
    filter_counts: [2, 2, 4, 4] # THE NUMBER OF FILTERS IN A POOLING KERNEL MUST MATCH THE NUMBER OF FILTERS IN THE PRECEEDING CONVOLUTIONAL LAYER KERNEL
    kernel_shapes: [[5, 5], [2, 2], [3, 3], [2, 2]]
    kernel_strides: [1, 2, 1, 2]
    cnn_activation_functions: ["leakyReLU", "none", "leakyReLU", "none"]
  mlp_architecture:
    neuron_counts: [1]
    mlp_activation_functions: ["sigmoid"]


#------------------------------------------------------------------------------------------------------------------------
test:
  test_dataset_size: 100
  show_results: true

parameters: 
  cnn_parameters_fpath: "./params/archive/pets/paramsCNN"
  mlp_parameters_fpath: "./params/archive/pets/paramsMLP"




