architecture:
  cnn_architecture:
    activation_fns:
    - leakyReLU
    - none
    - leakyReLU
    - none
    filter_counts:
    - 2
    - 2
    - 4
    - 4
    input_data_dim:
    - 1
    - 64
    - 64
    kernel_shapes:
    - - 5
      - 5
    - - 2
      - 2
    - - 3
      - 3
    - - 2
      - 2
    kernel_strides:
    - 1
    - 2
    - 1
    - 2
    type:
    - convolutional
    - max_pool
    - convolutional
    - max_pool
  mlp_architecture:
    activation_fns:
    - sigmoid
    neuron_counts:
    - 1
hyperparameters:
  cnn_hyperparameters:
    batch_size: 24
    dropout_rate: null
    lambda_L2: 0.001
    learn_rate: 0.01
    loss_func: BCELoss
    optimizer: adam
    reduction: mean
  mlp_hyperparameters:
    dropout_rate: null
    lambda_L2: 0.001
    learn_rate: 0.01
    optimizer: adam
log_id: logs/2025-07-13_12:55:21_cnn
specifications:
  multi_out: false
system:
  device: cpu
  mlp_save_fpath: ./params/cnn/pets/mlp
  save_fpath: ./params/cnn/pets
test:
  show_results: true
  test_dataset_size: 100
train:
  epochs: 600
  show_loss_plot: true
  train_dataset_size: 1000
