architecture:
  gate_activation_function: sigmoid
  gate_neuron_counts:
  - 64
  output_activation_function: none
  output_feature_count: 1
hyperparameters:
  batch_size: 64
  dropout_rate: null
  grad_clip_norm: null
  grad_clip_value: null
  lambda_L2: null
  learn_rate: 0.01
  loss_func: MSELoss
  optimizer: adam
  reduction: mean
log_id: logs/2025-05-26_20:48:05_lstm
parameters_fpath: ./params/paramsLSTM/vanilla
specs:
  auto_regressive: false
  device_type: cpu
  input_feature_count: 1
  stateful: false
test:
  show_results: true
  test_dataset_size: 50
train:
  epochs: 500
  show_loss_plot: true
  train_dataset_size: 500
