architecture:
  activations:
  - leakyReLU
  - leakyReLU
  - leakyReLU
  input_feature_count: 9
  neuron_counts:
  - 64
  - 64
  - 1
hyperparameters:
  batch_size: 128
  dropout_rate: null
  lambda_L2: 0.001
  learn_rate: 0.01
  loss_func: MSELoss
  optimizer: adam
  reduction: mean
log_id: logs/2025-07-13_11:09:55_mlp
specifications: null
system:
  device: cpu
  save_fpath: ./params/mlp
test:
  test_dataset_size: 100
train:
  epochs: 600
  show_loss_plot: true
  train_dataset_size: 500
