architecture:
  activation_functions:
  - leakyReLU
  - leakyReLU
  - leakyReLU
  neuron_counts:
  - 64
  - 64
  - 1
hyperparameters:
  batch_size: 128
  dropout_rate: null
  lambda_L2: 0.001
  learn_rate: 0.01
  loss_func: MSELoss
  optimizer: adam
  reduction: mean
log_id: logs/2025-06-18_17:52:17_mlp
parameters_fpath: ./params/mlp
specs:
  device_type: cpu
  input_feature_count: 9
test:
  show_results: false
  test_dataset_size: 100
train:
  epochs: 5000
  show_loss_plot: true
  train_dataset_size: 5000
