architecture:
  hidden_activation_function: sigmoid
  hidden_state_neuron_counts:
  - 64
  output_activation_function: none
  output_feature_count: 1
hyperparameters:
  batch_size: 3
  dropout_rate: null
  grad_clip_norm: null
  grad_clip_value: null
  lambda_L2: null
  learn_rate: 0.01
  loss_func: MSELoss
  optimizer: adam
  reduction: mean
log_id: logs/2025-05-26_14:47:36_rnn
parameters_fpath: ./params/paramsRNN/vanilla
specs:
  auto_regressive: false
  device_type: cpu
  input_feature_count: 1
  stateful: true
test:
  show_results: true
  test_dataset_size: 50
train:
  epochs: 1000
  show_loss_plot: true
  train_dataset_size: 500
