architecture:
  hidden_activation: sigmoid
  hidden_state_neuron_counts:
  - 64
  input_feature_count: 1
  output_activation: none
  output_feature_count: 1
hyperparameters:
  batch_size: 32
  dropout_rate: null
  grad_clip_norm: null
  grad_clip_value: null
  lambda_L2: null
  learn_rate: 0.01
  loss_func: MSELoss
  optimizer: adam
  reduction: mean
log_id: logs/2025-07-13_12:23:25_rnn
specifications:
  autoregressive: false
  stateful: true
system:
  device: cpu
  save_fpath: ./params/rnn/vanilla
test:
  show_results: true
  test_dataset_size: 50
train:
  epochs: 1000
  show_loss_plot: true
  train_dataset_size: 500
