architecture:
  hidden_activation: tanh
  hidden_state_neuron_counts:
  - 64
  input_feature_count: 100
  output_activation: reLU
  output_feature_count: 100
hyperparameters:
  batch_size: 32
  dropout_rate: null
  grad_clip_norm: null
  grad_clip_value: null
  lambda_L2: null
  learn_rate: 0.01
  loss_func: MSELoss
  optimizer: adam
  reduction: mean
log_id: logs/2025-07-13_13:04:36_text_rnn
specifications:
  autoregressive: false
  stateful: false
system:
  device: cpu
  save_fpath: ./params/rnn/text
test:
  show_results: false
  test_dataset_size: 5
train:
  epochs: 30000
  show_loss_plot: true
  train_dataset_size: 25
