specs:
  device_type: "cpu"
  input_feature_count: 100
  stateful: false

#------------------------------------------------------------------------------------------------------------------------
train:
  epochs: 30000
  train_dataset_size: 25
  show_loss_plot: true

hyperparameters:
    learn_rate: 0.01   
    batch_size: 4
    loss_func: "MSELoss"
    reduction: "mean"
    optimizer: "adam"
    lambda_L2: ~ #0.000006
    dropout_rate: ~

architecture:
    # hidden_state_neuron_counts: [16, 32, 64]
    # hidden_state_neuron_counts: [2, 4, 6]
    # hidden_state_neuron_counts: [4, 8]
    # hidden_state_neuron_counts: [16]
    output_feature_count: 100
    hidden_activation_function: "tanh"
    output_activation_function: "reLU"

#------------------------------------------------------------------------------------------------------------------------
test:
  test_dataset_size: 5


parameters_fpath: "./params/paramsRNN"

