architecture:
  ff_architecture:
    activation_fns:
    - leakyReLU
    - leakyReLU
    neuron_counts:
    - 2048
    - 512
  transformer_architecture:
    depth: 6
    num_heads: 8
hyperparameters:
  ff_hyperparameters:
    dropout_rate: null
    lambda_L2: null
    learn_rate: 0.01
    optimizer: null
  transformer_hyperparameters:
    batch_size: null
    dropout_rate: null
    lambda_L2: null
    learn_rate: 0.01
    loss_func: CELoss
    optimizer: null
    reduction: mean
log_id: logs/2025-07-10_00:39:45_transformer
parameters:
  ff_save_fpath: ./params/transformer/transformer_ff
  transformer_save_fpath: ./params/transformer
specs:
  device_type: cpu
  input_feature_count: 512
  type: both
test:
  show_results: false
  test_dataset_size: null
train:
  epochs: 500
  show_loss_plot: true
  train_dataset_size: 10
